function click_me(){
    document.getElementById("id1").innerHTML="Dubai Scholars Private School is an international private school, located in Al Qusais, Dubai, UAE. The school is managed by the Scholars International Group, and offers the National Curriculum of England to students ranging from FS1 to Year 13.";
  }
  function click_me2(){
    document.getElementById("id1").innerHTML="Founded in 1976 by Madhu Verma, Dubai Scholars Private School was a villa-based school, located in the Deira area of Dubai. Eventually, the school relocated to two villas, later expanding to seven In 1994, the school relocated to the Al Qusais area of Dubai, where the campus is now located.";
  }
  function click_me3(){
    document.getElementById("id1").innerHTML="I believe that Dubai Scholars is a prestigious school where rules are reinforced and bullying is almost none existent.Students are taught well by teachers and are all included which makes this school very good. ";
  }
  function click_me4(){
      document.getElementById("id1").innerHTML="Dubai Scholars Private School follows the National Curriculum of England, offering courses for students ranging from FS 1 to Year 13.During the foundation programme and primary school years (FS 1-Year 6), students will study a defined set of subjects in order to prepare them for the secondary school. As per UAE's Ministry of Education requirements, all of the students will also study Arabic, and the Muslim students will also take Islamic studies.During Years 8 and 9 (Key Stage 3), students will keep studying a general set of subjects, preparing for the IGCSE programme."
  }
  function showChange(){
    var a=document.getElementById("id2").value;
    alert(" You have selected "+a);
}